### ISSUE TITLE
How to change the background color?

### ISSUE THREAD

**Issue by arorakanav11** [tnicola/ngx-joyride#14]
I want to do away with the background color, is there a way. 

P.s: it would be awesome if there are different color controls for title button and the background

**Comment by tnicola** [comment]
Hi @arorakanav11, 
Have you tried the `themeColor` property?

```
this.joyrideService.startTour(
      { steps: ['firstStep', 'secondStep'], 
        themeColor; '#3b5560'
      } );
```
 themeColor can change backdrop, buttons and title color. If you need something more specific, you can just override the CSS.

**Comment by tnicola** [comment]
Having a full customization would be nice but it requires to have lots of options to handle for each element (colors, dimensions, shadows, fonts, paddings and so on), I think overriding CSS is more a natural solution. Otherwise I could find the most wanted elements to customize or provide a set of predefined themes. I'm open to any suggesion!
