### ISSUE TITLE
error after implementation of ngx-joyride

### ISSUE THREAD

**Issue by hvaishnav** [tnicola/ngx-joyride#228]
I am building an angular application where I need to show the guided tour for my website. To achieve this purpose I have used ngx-joyride but after implementation of it.

I am getting this error on every page. Please help me to resolve the issue and tell me the reason behind that.

I am attaching the image
![FwNwn](https://user-images.githubusercontent.com/38201417/92210031-a4355b80-eeab-11ea-9604-d52aeb86fe32.png)(Image to refer)

**Comment by sted6** [comment]
The error is being generated because you're applying the same joyrideStep property to more than one element/component. This usually happens when you're applying the joyrideStep property to an element/component inside an ngFor loop or to a component that is used in more than one place.

As long as your tour is working properly you can just disable the error by setting logsEnabled to false.

If your tour isn't working properly and its inside an ngFor loop, you can use a ternary expression to dynamically set the joyrideStep property.

`<app-example *ngFor="let example of examples; let i = index" [joyrideStep]="conditionToBeMet ? 'stepName' : 'stepName' + i"></app-example>`
