### ISSUE TITLE
Is there any event when the tour is finished?

### ISSUE THREAD

**Issue by diximus** [tnicola/ngx-joyride#5]
Hello,

I've searched on the code but i couldn't find any way to subscribe when the tour is finished.

Is this implemented?

Thank you in advance

EDIT: I'm able to do this with the JoyrideStepsContainerService and checking if it's the last step. Our customer will probably want this implemented, if there isn't any implementation for this i'll try to write it.

**Comment by tnicola** [comment]
Hi @diximus ,
No, there isn't any event fired at the end of the tour at the moment. I'm currently working on that. More in general I'd like to fire events and also give to the final user the possibility to pass functions like onNext(), onStart(), onEnd(). 

Thanks for asking. Feel free to contribute if you need the feature asap, otherwise, just wait for the next release. In the meanwhile, any suggestion is appreciated.

**Comment by diximus** [comment]
Hi,

Nice to know that! I'm still waiting for a confirmation from the customer, this project will start within 3 or 4 weeks if accepted.

**Comment by tnicola** [comment]
ngx-joyride@2.0.0 has been released. Now you have some `@Output` properties like next, prev and done in the joyrideStep directive. You can also subscribe to `startTour(...)` in this way:

 ```typescript
@Component({
  selector: 'app-component',
  template: `<div joyrideStep="joy1" title="title" (prev)="onPrev()" (next)="onNext()">Hello!</div>
             <div joyrideStep="joy2" title="title2" (done)="onDone()">Hello!</div>`
})
export class AppComponent {
  constructor(private readonly joyrideService: JoyrideService) { }

  onClick() {
    this.joyrideService.startTour({ steps: ['joy1', 'joy2']}).subscribe(
      (step) => { /*Do something*/},
      (error) => { /*handle error*/},
      () => { /*Tour is finished here, do something*/}
    );
  }
}
 ```

**Comment by diximus** [comment]
Thank you!

I've just updated now. The subscription fits really well where, this is exactly what i was looking for.
